//login
TXT.login_waiting="正在登录请稍后";
TXT.login_name="用户名";
TXT.login_password="密码";
TXT.login_btn_login="登录";
TXT.login_btn_close="登录";
TXT.login_page="登录页面";
TXT.login_title="用户登录";
TXT.login_tip="提示";
TXT.login_invalidusername="用户名不能为空";
TXT.login_invalidpassword="口令不能为空"
TXT.login_notExist="用户名错误"
TXT.login_errorPassword="口令错误"
TXT.login_userOnline="该用户已经登录,请稍后再试";
TXT.login_lock="该用户账号已被锁定，请与管理员联系";
TXT.login_disable="用户名已失效";
TXT.login_max_connection="连接数量已达到最大值，请稍后再试";
TXT.login_license_not_found="License文件未找到";