update BLC_SKU set DEFAULT_PRODUCT_ID = (
select PRODUCT_ID from BLC_PRODUCT_SKU_XREF where BLC_PRODUCT_SKU_XREF.SKU_ID=BLC_SKU.SKU_ID
);

update BLC_SKU set BLC_SKU.PRODUCT_ID = (
select  PRODUCT_ID from BLC_PRODUCT where DEFAULT_SKU_ID = BLC_SKU.SKU_ID
) where BLC_SKU.PRODUCT_ID is null;

CREATE SCHEMA `guoph` DEFAULT CHARACTER SET utf8 ;

