/*!40014 SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0 */;
/*!40101 SET character_set_client = utf8 */;

ALTER TABLE nph_order ADD COLUMN is_delivery_info_sent TINYINT(1) DEFAULT 0;
ALTER TABLE nph_order ADD COLUMN is_shipped TINYINT(1) DEFAULT 0;
ALTER TABLE nph_order ADD COLUMN delivery_type VARCHAR(20) DEFAULT NULL
COMMENT 'PICKUP - 自提, LOGISTICS - 物流, EXPRESS - 快递';

ALTER TABLE nph_order_log ADD COLUMN remark VARCHAR(255) DEFAULT NULL;
ALTER TABLE nph_order_log ADD COLUMN is_display TINYINT(1) DEFAULT 1;

# 2015/07/16 steven #

CREATE TABLE IF NOT EXISTS ph_pickup_address (
  `pickup_address_id` BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `provider_id`       BIGINT(20)   NOT NULL,
  `sender`            VARCHAR(20)  NOT NULL,
  `phone`             VARCHAR(20)  NOT NULL,
  `address`           VARCHAR(100) NOT NULL,
  `remark`            VARCHAR(100) NOT NULL,
  `is_default`        TINYINT(1)            DEFAULT 0,
  `date_created`      DATETIME              DEFAULT NULL,
  `created_by`        BIGINT(20)            DEFAULT NULL,
  `date_updated`      DATETIME              DEFAULT NULL,
  `updated_by`        BIGINT(20)            DEFAULT NULL,
  PRIMARY KEY (`pickup_address_id`)
);

ALTER TABLE nph_order_item
ADD COLUMN delivery_type VARCHAR(20) DEFAULT NULL,
ADD COLUMN pickup_address_id BIGINT(20) DEFAULT NULL;

ALTER TABLE ph_pickup_address
ADD COLUMN name VARCHAR(20) NOT NULL;

# 2015/07/17 chet #
ALTER TABLE nph_sku
ADD COLUMN param_description LONGTEXT DEFAULT NULL;

ALTER TABLE nph_order_address
ADD COLUMN delivery_type VARCHAR(20) DEFAULT NULL,
ADD COLUMN pickup_address_id BIGINT(20) DEFAULT NULL;

ALTER TABLE nph_provider
ADD COLUMN is_support_pickup TINYINT(1) DEFAULT 0;
# 2015/07/17 steven #

# 2015/07/25 chet #
CREATE TABLE IF NOT EXISTS `ph_refund` (
  `refund_id`     BIGINT(10) NOT NULL,
  `refund_desc`   VARCHAR(200) DEFAULT NULL
  COMMENT '退货描述',
  `refund_status` VARCHAR(10)  DEFAULT NULL
  COMMENT '退货状态 PENDING-待审核 APPROVE-审核通过 REFUSED-拒绝通过',
  `refund_time`   DATETIME     DEFAULT NULL
  COMMENT '退款时间',
  `refund_by`     VARCHAR(45)  DEFAULT NULL
  COMMENT '退款经办人',
  `order_item_id` BIGINT(20)   DEFAULT NULL
  COMMENT '申请退款订单项',
  `refund_num`    INT(11)      DEFAULT NULL
  COMMENT '申请退款数量',
  PRIMARY KEY (`refund_id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `ph_refund_media` (
  `refund_media_id` BIGINT(10) NOT NULL,
  `refund_id`       BIGINT(10)   DEFAULT NULL,
  `media_url`       VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`refund_media_id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE ph_express (
  `express_no`       VARCHAR(60) NOT NULL,
  `order_no`         VARCHAR(60) NOT NULL,
  `receiver`         VARCHAR(60)  DEFAULT NULL,
  `receiver_phone`   VARCHAR(60)  DEFAULT NULL,
  `receiver_address` VARCHAR(255) DEFAULT NULL,
  `sender`           VARCHAR(60)  DEFAULT NULL,
  `sender_phone`     VARCHAR(60)  DEFAULT NULL,
  `sender_address`   VARCHAR(255) DEFAULT NULL,
  `description`      VARCHAR(255) DEFAULT NULL,
  `date_created`     DATETIME     DEFAULT NULL,
  PRIMARY KEY (`express_no`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
  
# 2015/07/26 chet #
CREATE TABLE `ph_compare_price` (
  `COMPARE_PRICE_ID` bigint(20) NOT NULL,
  `NAME` varchar(45) DEFAULT NULL COMMENT '商品名称',
  `PRICE` decimal(19,2) DEFAULT NULL COMMENT '商品价格',
  `SOURCE` varchar(100) DEFAULT NULL COMMENT '商品信息来源名称',
  `SOURCE_URL` varchar(100) DEFAULT NULL COMMENT '商品信息来源URL链接',
  `CREATE_TIME` datetime DEFAULT NULL,
  PRIMARY KEY (`COMPARE_PRICE_ID`)
) 
  ENGINE=InnoDB 
  DEFAULT CHARSET=utf8;

CREATE TABLE `ph_sku_compare_price` (
  `SKU_ID` bigint(20) NOT NULL,
  `COMPARE_PRICE_ID` bigint(20) NOT NULL
) 
  ENGINE=InnoDB 
  DEFAULT CHARSET=utf8;

ALTER TABLE `nph_address` ADD COLUMN `community` VARCHAR(20)
AFTER `district`;
ALTER TABLE `nph_order_address` ADD COLUMN `community` VARCHAR(20)
AFTER `district`;

# 2015/07/29 chet #
ALTER TABLE `ph_coupon` 
ADD COLUMN `EVENT` VARCHAR(45) NULL AFTER `DESC`,
ADD COLUMN `ISSUE_PRIORITY` INT NOT NULL DEFAULT 10
AFTER `EVENT`,
ADD COLUMN `NUMBER` INT NOT NULL DEFAULT 1
AFTER `ISSUE_PRIORITY`,
ADD COLUMN `VALUE` DECIMAL(19,2) NULL AFTER `NUMBER`;
ALTER TABLE `ph_coupon` 
CHANGE COLUMN `DESC` `NAME` VARCHAR(45) NULL DEFAULT NULL ;

ALTER TABLE `ph_coupon_attribute` 
ADD COLUMN `CATEGORY` VARCHAR(45) NULL AFTER `VALUE`;

ALTER TABLE `ph_customer_coupon` 
ADD COLUMN `NUMBER` INT NULL AFTER `STATUS`;

ALTER TABLE `ph_coupon` 
ADD COLUMN `SCOPE` VARCHAR(45) NULL AFTER `VALUE`;

ALTER TABLE `nph_order`
ADD COLUMN `provider_id` BIGINT(20) NULL;

# 2015/08/04 chet #
ALTER TABLE `nph_provider` 
ADD COLUMN `PROVIDER_EN_NAME` VARCHAR(45) NULL AFTER `is_support_pickup`,
ADD COLUMN `PROVIDER_EMAIL` VARCHAR(45) NULL AFTER `PROVIDER_EN_NAME`;

# 2015/08/05 chet #
ALTER TABLE `ph_compare_price` 
ADD COLUMN `SKU_ID` BIGINT(20) NULL AFTER `CREATE_TIME`;

DROP TABLE `ph_sku_compare_price`;

# 2015/08/06 steven #
ALTER TABLE `nph_customer`
ADD COLUMN `created_by` BIGINT(20) NULL,
ADD COLUMN `updated_by` BIGINT(20) NULL;

# 2015/08/06 chet #
CREATE TABLE `ph_customer_message` (
  `CUSTOMER_MESSAGE_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `MESSAGE_TEXT` VARCHAR(225) NULL,
  `MESSAGE_TYPE` VARCHAR(20) NULL,
  `CREATE_TIME` DATETIME NULL,
  `CUSTOMER_ID` BIGINT(20) NULL,
  `STATUS` VARCHAR(10) NULL,
  `URL` VARCHAR(100) NULL,
  PRIMARY KEY (`CUSTOMER_MESSAGE_ID`));
  
  ALTER TABLE `ph_customer_message` 
CHANGE COLUMN `MESSAGE_TEXT` `MESSAGE_TEXT` LONGTEXT NULL ,
CHANGE COLUMN `MESSAGE_TYPE` `MESSAGE_TITLE` VARCHAR(50) NULL DEFAULT NULL ;

# 2015/08/12 chet #
CREATE TABLE `ph_group_on` (
  `GROUP_ON_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SKU_ID` bigint(20) DEFAULT NULL,
  `SKU_QUANTITY` int(11) DEFAULT NULL,
  `PARTICIPATE_IN_COUNT` int(11) DEFAULT NULL COMMENT '参与团购人数',
  `RULE_DESC` longtext DEFAULT NULL COMMENT '团购规则描述',
  `START_DATE` datetime DEFAULT NULL COMMENT '团购开始时间',
  `END_DATE` datetime DEFAULT NULL COMMENT '团购截止时间',
  PRIMARY KEY (`GROUP_ON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ph_group_on_attr` (
  `GROUP_ON_ATTR_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `GROUP_ON_ID` bigint(20) DEFAULT NULL,
  `COUNT_RANGE_FROM` int(11) DEFAULT NULL,
  `COUNT_RANGE_TO` int(11) DEFAULT NULL,
  `PRICE` decimal(19,5) DEFAULT NULL,
  PRIMARY KEY (`GROUP_ON_ATTR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `nph_sku` 
ADD COLUMN `IS_GROUP_ON` TINYINT(1) NULL DEFAULT 0 AFTER `PARAM_DESCRIPTION`;

ALTER TABLE `nph_order` 
ADD COLUMN `group_on_id` BIGINT(20) NULL AFTER `provider_id`,
ADD COLUMN `is_group_on` TINYINT(1) NULL DEFAULT 0 AFTER `group_on_id`;

# 2015/08/13 steven #
ALTER TABLE `nph_order`
ADD COLUMN `confirm_date` DATETIME NULL AFTER `submit_date`;

# 2015/08/15 chet #
ALTER TABLE `nph_sku` 
ADD COLUMN `IS_SECKILLING` TINYINT(1) NULL DEFAULT 0 COMMENT '是否为秒杀商品' AFTER `IS_GROUP_ON`,
ADD COLUMN `SECKILLING_START_DATE` DATETIME NULL COMMENT '秒杀开始时间' AFTER `IS_SECKILLING`,
ADD COLUMN `SECKILLING_END_DATE` DATETIME NULL COMMENT '秒杀结束时间' AFTER `SECKILLING_START_DATE`,
ADD COLUMN `LIMIT_NUM` INT(11) NULL COMMENT '秒杀活动单个用户购买此商品的最大数目' AFTER `SECKILLING_END_DATE`;

#2015/08/20 chet #
ALTER TABLE `nph_sku` 
ADD COLUMN `IS_OFF_LINE` TINYINT(1) NULL DEFAULT 0 AFTER `LIMIT_NUM`;

#2015/08/25 chet #
CREATE TABLE `ph_coupon_code` (
  `COUPON_CODE_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` BIGINT(20) NULL,
  `START_DATE` DATETIME NULL,
  `END_DATE` DATETIME NULL,
  `COUPON_CODE` VARCHAR(20) NULL,
  `COUPON_AMOUNT` DECIMAL(9,3) NULL,
  `COUPON_AMOUNT_TWO` DECIMAL(9,3) NULL,
  `STATUS` VARCHAR(15) NULL,
  PRIMARY KEY (`COUPON_CODE_ID`));

ALTER TABLE `nph_order` 
ADD COLUMN `APPLY_COUPON_CODE_ID` BIGINT(20) NULL AFTER `APPLY_COUPON_ID`;

ALTER TABLE `nph_order` 
ADD COLUMN `ORDER_COUPON_CODE_DISCOUNT` DECIMAL(19,5) NULL AFTER `ORDER_COUPON_DISCOUNT`;

#2015/08/25 jenny#
ALTER TABLE `nph_rating_detail`
ADD COLUMN `LOGISTICS_RATING` DOUBLE NOT NULL COMMENT '' AFTER `RATING_SUMMARY_ID`,
ADD COLUMN `SERVE_RATING` DOUBLE NOT NULL COMMENT '' AFTER `LOGISTICS_RATING`;

#2015/08/25 chet #
ALTER TABLE `ph_coupon_code` 
ADD COLUMN `COUPON_ID` BIGINT(20) NULL AFTER `CUSTOMER_ID`;

ALTER TABLE `nph_sku` 
ADD COLUMN `IS_CODE_SUPPORT` TINYINT(1) NULL DEFAULT 0 AFTER `IS_OFF_LINE`;
#2015/08/26#
/*ALTER TABLE `globalph`.`nph_rating_summary`
ADD COLUMN `LOGISTICS_AVERAGE_RATING` DOUBLE NOT NULL COMMENT '' AFTER `RATING_TYPE`,
ADD COLUMN `SERVE_AVERAGE_RATING` DOUBLE NOT NULL COMMENT '' AFTER `LOGISTICS_AVERAGE_RATING`;*/

#2015/09/06 chet #
ALTER TABLE `nph_sku` 
ADD COLUMN `IS_PRESALE` TINYINT(1) NULL DEFAULT 0 AFTER `IS_CODE_SUPPORT`;

#2015/09/06 jenny#
ALTER TABLE `globalph`.`nph_order`
ADD COLUMN `remark` VARCHAR(500) NULL COMMENT '' AFTER `is_group_on`;

#2015/09/09 jenny#
ALTER TABLE `globalph`.`ph_group_on`
ADD COLUMN `GROUP_PRICE` DECIMAL(19,5) NOT NULL COMMENT '' AFTER `END_DATE`,
ADD COLUMN `GROUP_UNIT` VARCHAR(20) NOT NULL COMMENT '' AFTER `GROUP_PRICE`,
ADD COLUMN `MIN_COUNT` INT(11) NULL DEFAULT 1 COMMENT '' AFTER `GROUP_UNIT`;

ALTER TABLE `globalph`.`ph_group_on`
CHANGE COLUMN `PARTICIPATE_IN_COUNT` `PARTICIPATE_IN_COUNT` INT(11) NULL DEFAULT 0 COMMENT '参与团购人数' ;

#2015/09/09 chet#
ALTER TABLE `nph_order` 
ADD COLUMN `COMPLETE_DATE` DATETIME NULL AFTER `confirm_date`;

ALTER TABLE `ph_refund` 
ADD COLUMN `ORDER_ID` BIGINT(20) NULL AFTER `REFUND_BY`;
ALTER TABLE `globalph`.`nph_wechat_customer`
CHANGE COLUMN `is_from_wechat` `is_from_rrm` TINYINT(1) DEFAULT '0';

ALTER TABLE `globalph`.`nph_address`
CHANGE COLUMN `is_from_wechat` `is_from_rrm` TINYINT(1) DEFAULT '0';

#2015/09/10 jenny#
ALTER TABLE `globalph`.`nph_sku`
ADD COLUMN `IS_POINT_SUPPORT` TINYINT(1) NULL DEFAULT 0
COMMENT ''
AFTER `IS_PRESALE`;

#2015/09/14 jenny#
ALTER TABLE `globalph`.`nph_order`
ADD COLUMN `ORDER_DEDUCTIONBONUS` INT(11) NULL DEFAULT 0
COMMENT ''
AFTER `REMARK`;

/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;